name: Testovi

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Preuzmi kod
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Podesi .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Instaliraj SonarCloud skener
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarCloud pocetak analize
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner begin /k:"AleksandraArr_AutoSkola" /o:"aleksandraarr" /d:sonar.token="$env:SONAR_TOKEN" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" /d:sonar.coverage.exclusions="Client/**,Server/Form1.cs,Server/Form1.Designer.cs,Server/Program.cs,Client/Program.cs,Server/Server.cs,Server/ClientHandler.cs,Server/Controller.cs,Common/Communication/**,Broker/DbConnection.cs"

      - name: Start SQL LocalDB
        run: SqlLocalDB.exe start MSSQLLocalDB

      - name: Kreiraj test bazu
        run: sqlcmd -S "(localdb)\mssqllocaldb" -i AutoSkolaTest.sql

      - name: Build
        run: dotnet build Tests/Tests.csproj

      - name: Pokreni testove
        run: dotnet test Tests/Tests.csproj --no-build --collect:"XPlat Code Coverage" --results-directory TestResults -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: SonarCloud kraj analize
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="$env:SONAR_TOKEN"
